### ISSUE TITLE
def unquote makes Styler fail to format a file

### ISSUE THREAD

**Issue by simonprev** [adobe/elixir-styler#41]
Some non-traditional meta-programming makes Styler fail to format a file

This only happen when updating from 0.7.2 to 0.7.7

## Elixir / OTP Version

Elixir 1.14.2 (compiled with Erlang/OTP 25)

## Example Input

```elixir
defmodule StylerBug do
  @a []

  for {name, value} <- @a do
    def unquote(name)(), do: unquote(value)
  end
end
```

## Current behaviour / Stacktrace

```
$ mix format
mix format failed for file: lib/styler_bug.ex
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an atom

    :erlang.atom_to_binary({:unquote, [closing: [line: 2], line: 2], [{:name, [line: 2], nil}]})
    (elixir 1.14.2) lib/code/formatter.ex:280: Code.Formatter.quoted_to_algebra/3
    (elixir 1.14.2) lib/code/formatter.ex:1650: anonymous fn/5 in Code.Formatter.args_to_algebra_with_comments/7
    (elixir 1.14.2) lib/code/formatter.ex:1668: Code.Formatter.args_to_algebra_with_comments/7
    (elixir 1.14.2) lib/code/formatter.ex:1127: Code.Formatter.call_args_to_algebra_no_blocks/6
    (elixir 1.14.2) lib/code/formatter.ex:1100: Code.Formatter.call_args_to_algebra/6
    (elixir 1.14.2) lib/code/formatter.ex:1048: Code.Formatter.local_to_algebra/5
    (elixir 1.14.2) lib/code/formatter.ex:576: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
```

## Expected Output

```elixir
defmodule StylerBug do
  @a []

  for {name, value} <- @a do
    def unquote(name)(), do: unquote(value)
  end
end
```

**Comment by novaugust** [comment]
Thanks for the issue! Fun one to figure out =)

**Comment by novaugust** [comment]
Pushed out 0.7.8 if you want to take it for a spin
