### ISSUE TITLE
Unicode in Erlang single quoted strings raises ArgumentError

### ISSUE THREAD

**Issue by fhunleth** [adobe/elixir-styler#45]
## Elixir / OTP Version

```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```

This was run using the current `.tool-versions` file in this project, but Elixir 1.14.4 also has this issue.

## Example Input

```elixir
      def format(ns)  do
         :io_lib.format('~.1f μs', [ns / 1000])
      end
```

## Current behaviour / Stacktrace

```
**Style created invalid ast:**: {:def, [do: [line: 1], end: [line: 3], line: 1],
 [
   {:format, [closing: [line: 1], line: 1], [{:ns, [line: 1], nil}]},
   [
     {{:__block__, [line: 1], [:do]},
      {{:., [line: 2], [{:__block__, [line: 2], [:io_lib]}, :format]},
       [closing: [line: 2], line: 2],
       [
         {:__block__, [delimiter: "'", line: 2],
          [[126, 46, 49, 102, 32, 956, 115]]},
         {:__block__, [closing: [line: 2], line: 2],
          [
            [
              {:/, [line: 2],
               [
                 {:ns, [line: 2], nil},
                 {:__block__, [token: "1000", line: 2], [1000]}
               ]}
            ]
          ]}
       ]}}
   ]
 ]}


  1) test erlang strings (Styler.Style.StringTest)
     test/style/string_test.exs:14
     ** (ArgumentError) cannot convert the given list to a string.
     
     To be converted to a string, a list must either be empty or only
     contain the following elements:
     
       * strings
       * integers representing Unicode code points
       * a list containing one of these three elements
     
     Please check the given list or call inspect/1 to get the list representation, got:
     
     [{:__block__, [line: 1, token: "126"], '~'}, {:__block__, [line: 1, token: "46"], '.'}, {:__block__, [line: 1, token: "49"], '1'}, {:__block__, [line: 1, token: "102"], 'f'}, {:__block__, [line: 1, token: "32"], ' '}, {:__block__, [line: 1, token: "956"], [956]}, {:__block__, [line: 1, token: "115"], 's'}]
     
     stacktrace:
       (elixir 1.14.2) lib/list.ex:1084: List.to_string/1
       (elixir 1.14.2) lib/code/formatter.ex:384: Code.Formatter.quoted_to_algebra/3
       (elixir 1.14.2) lib/code/formatter.ex:1650: anonymous fn/5 in Code.Formatter.args_to_algebra_with_comments/7
       (elixir 1.14.2) lib/code/formatter.ex:1960: Code.Formatter.each_quoted_to_algebra_with_comments/6
       (elixir 1.14.2) lib/code/formatter.ex:1938: Code.Formatter.quoted_to_algebra_with_comments/6
       (elixir 1.14.2) lib/code/formatter.ex:1676: Code.Formatter.args_to_algebra_with_comments/7
       (elixir 1.14.2) lib/code/formatter.ex:1167: Code.Formatter.call_args_to_algebra_no_blocks/6
       (elixir 1.14.2) lib/code/formatter.ex:1100: Code.Formatter.call_args_to_algebra/6
       (elixir 1.14.2) lib/code/formatter.ex:994: Code.Formatter.remote_to_algebra/3
       (elixir 1.14.2) lib/code/formatter.ex:576: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
       (elixir 1.14.2) lib/code/formatter.ex:1960: Code.Formatter.each_quoted_to_algebra_with_comments/6
       (elixir 1.14.2) lib/code/formatter.ex:1938: Code.Formatter.quoted_to_algebra_with_comments/6
       (elixir 1.14.2) lib/code/formatter.ex:581: Code.Formatter.block_args_to_algebra/4
       (elixir 1.14.2) lib/code/formatter.ex:1858: Code.Formatter.clauses_to_algebra/4
       (elixir 1.14.2) lib/code/formatter.ex:1260: Code.Formatter.do_end_block_to_algebra/5
       (elixir 1.14.2) lib/code/formatter.ex:1251: Code.Formatter.do_end_blocks_to_algebra/2
       (elixir 1.14.2) lib/code/formatter.ex:1091: Code.Formatter.call_args_to_algebra/6
       (elixir 1.14.2) lib/code/formatter.ex:1048: Code.Formatter.local_to_algebra/5
       (elixir 1.14.2) lib/code/formatter.ex:576: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
       (elixir 1.14.2) lib/code/formatter.ex:1960: Code.Formatter.each_quoted_to_algebra_with_comments/6
```
## Expected Output

If you delete the `μ`, it works as expected. 

I naively thought that this would be some variation of IOData vs. Chardata, because:

```
iex> [956] |> IO.chardata_to_string        
"μ"
iex> [956] |> IO.iodata_to_binary  
** (ArgumentError) errors were found at the given arguments:
```

I started debugging and didn't see anything in Styler that I thought would do this, but this case works fine with regular `mix format`.  Maybe that's a hint. I'll keep digging when I have time next, but figured you all might know offhand.

There's a trivial workaround which is to change the Erlang string from using quotes to using the `~c` sigil.

**Comment by novaugust** [comment]
thanks for the issue frank!

you can see the difference in what the AST for a charlist looks like from `quote do` vs from Styler's wrapper of Code.string_to_quoted_with_comments

this is a result of the way that we're using elixir's Code module to get metadata about literals that you normally wouldn't get in AST. While our method works with every other node, seems like single-quote charlist literals are verboten.

```iex
iex(3)> Styler.string_to_quoted_with_comments "'~.1f μs'"
{{:__block__, [delimiter: "'", line: 1], [[126, 46, 49, 102, 32, 956, 115]]},
 []}
iex(4)> Styler.quoted_to_string(quote do '~.1f μs' end, [])
"[126, 46, 49, 102, 32, 956, 115]\n"
iex(5)> {ast, comments} = Styler.string_to_quoted_with_comments "'~.1f μs'"
{{:__block__, [delimiter: "'", line: 1], [[126, 46, 49, 102, 32, 956, 115]]},
 []}
iex(6)> Styler.quoted_to_string(ast, comments)
** (ArgumentError) cannot convert the given list to a string.
```

(in other words, it's not a rewrite that's breaking stuff, it's just us wanting data 😭 )

I'll open an issue w/ elixir later today and see if Jose cares about it (he might not, this explosion is caveated in the docs), but either way given that using the `~c` sigil fixes the issue, i could update styler to change all `'charlist'` instances into `~c"charlist"` to fix this bug

**Comment by novaugust** [comment]
I personally almost never use charlists in my code these days. Would you be mad at the tool if it turned all your `'charlist'` into `~c"charlist"`?

**Comment by fhunleth** [comment]
@novaugust I'd fully support conversion to `~c"charlist"`. In fact, that's actually what I was looking into doing with styler, so your proposed fix is perfect!!!

**Comment by novaugust** [comment]
I'll marked this closed by https://github.com/adobe/elixir-styler/pull/46 then =) Will kick out 0.7.10 shortly

**Comment by novaugust** [comment]
0.7.10 is out ~~ thanks again for the issue + feedback frank

**Comment by novaugust** [comment]
Ah the one downside - i made it `~c''`, not `~c""`, as if i went with `"` i'd have to escape `"` and that sounded like too much work on the spot
